package beans;
// Generated 17.05.2020. 19.35.51 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import util.HibernateUtil;




/**
 * Ocene generated by hbm2java
 */
public class Ocene  implements java.io.Serializable {


     private Integer idO;
     private Onlineprodavnica onlineprodavnica;
     private Poljoprivrednik poljoprivrednik;
     private int ocena;
     private String komentar;

    public Ocene() {
    }

    public Ocene(Onlineprodavnica onlineprodavnica, Poljoprivrednik poljoprivrednik, int ocena, String komentar) {
       this.onlineprodavnica = onlineprodavnica;
       this.poljoprivrednik = poljoprivrednik;
       this.ocena = ocena;
       this.komentar = komentar;
    }
   
    public Integer getIdO() {
        return this.idO;
    }
    
    public void setIdO(Integer idO) {
        this.idO = idO;
    }
    public Onlineprodavnica getOnlineprodavnica() {
        return this.onlineprodavnica;
    }
    
    public void setOnlineprodavnica(Onlineprodavnica onlineprodavnica) {
        this.onlineprodavnica = onlineprodavnica;
    }
    public Poljoprivrednik getPoljoprivrednik() {
        return this.poljoprivrednik;
    }
    
    public void setPoljoprivrednik(Poljoprivrednik poljoprivrednik) {
        this.poljoprivrednik = poljoprivrednik;
    }
    public int getOcena() {
        return this.ocena;
    }
    
    public void setOcena(int ocena) {
        this.ocena = ocena;
    }
    public String getKomentar() {
        return this.komentar;
    }
    
    public void setKomentar(String komentar) {
        this.komentar = komentar;
    }


    public static List<Ocene> dohvatiOcene(int idProizvod){
         List<Ocene> ocene = new ArrayList<Ocene>();
         SessionFactory sf = HibernateUtil.getSessionFactory();
         Session session = sf.openSession();
         session.beginTransaction();
         
         String upit="from Ocene o where o.onlineprodavnica.idPro = :idProizvod";
         Query query = session.createQuery(upit);
         query.setParameter("idProizvod", idProizvod);
         ocene = query.list();
         
         session.getTransaction().commit();
         session.close();
         
         return ocene;
    }
    
    public static boolean proveraKomentara(String username, int idProizvod){
        boolean status=true;
         SessionFactory sf = HibernateUtil.getSessionFactory();
         Session session = sf.openSession();
         session.beginTransaction();
         
         String upit="from Ocene o where o.onlineprodavnica.idPro = :idProizvod and o.poljoprivrednik.usernamePoljo = :username";
         Query query = session.createQuery(upit);
         query.setParameter("idProizvod", idProizvod);
         query.setParameter("username", username);
         Ocene ocena=(Ocene) query.uniqueResult();
         
         
         session.getTransaction().commit();
         session.close();
         if(ocena!=null){
             status=false;
         }
         return status;
    }
    
      public static void dodajOcenu(Ocene ocena){
         
        SessionFactory sf=HibernateUtil.getSessionFactory();
        Session session = sf.openSession();
        session.beginTransaction();
        
        session.save(ocena);
        session.getTransaction().commit();
        session.close();
    }
      

}


