package beans;
// Generated 17.05.2020. 19.35.51 by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import org.hibernate.Criteria;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.criterion.Restrictions;
import util.HibernateUtil;

/**
 * Poljoprivrednik generated by hbm2java
 */
public class Poljoprivrednik  implements java.io.Serializable {


     private String usernamePoljo;
     private Korisnik korisnik;
     private String ime;
     private String prezime;
     private Date datumRodjenja;
     private String mestoRodjenja;
     private String telefon;
     private String email;
     private Set<Rasadnik> rasadniks = new HashSet<Rasadnik>(0);
     private Set<Ocene> ocenes = new HashSet<Ocene>(0);

    public Poljoprivrednik() {
    }

	
    public Poljoprivrednik(Korisnik korisnik, String ime, String prezime, Date datumRodjenja, String mestoRodjenja, String telefon, String email) {
        this.korisnik = korisnik;
        this.ime = ime;
        this.prezime = prezime;
        this.datumRodjenja = datumRodjenja;
        this.mestoRodjenja = mestoRodjenja;
        this.telefon = telefon;
        this.email = email;
    }
    public Poljoprivrednik(Korisnik korisnik, String ime, String prezime, Date datumRodjenja, String mestoRodjenja, String telefon, String email, Set<Rasadnik> rasadniks, Set<Ocene> ocenes) {
       this.korisnik = korisnik;
       this.ime = ime;
       this.prezime = prezime;
       this.datumRodjenja = datumRodjenja;
       this.mestoRodjenja = mestoRodjenja;
       this.telefon = telefon;
       this.email = email;
       this.rasadniks = rasadniks;
       this.ocenes = ocenes;
    }
   
    public String getUsernamePoljo() {
        return this.usernamePoljo;
    }
    
    public void setUsernamePoljo(String usernamePoljo) {
        this.usernamePoljo = usernamePoljo;
    }
    public Korisnik getKorisnik() {
        return this.korisnik;
    }
    
    public void setKorisnik(Korisnik korisnik) {
        this.korisnik = korisnik;
    }
    public String getIme() {
        return this.ime;
    }
    
    public void setIme(String ime) {
        this.ime = ime;
    }
    public String getPrezime() {
        return this.prezime;
    }
    
    public void setPrezime(String prezime) {
        this.prezime = prezime;
    }
    public Date getDatumRodjenja() {
        return this.datumRodjenja;
    }
    
    public void setDatumRodjenja(Date datumRodjenja) {
        this.datumRodjenja = datumRodjenja;
    }
    public String getMestoRodjenja() {
        return this.mestoRodjenja;
    }
    
    public void setMestoRodjenja(String mestoRodjenja) {
        this.mestoRodjenja = mestoRodjenja;
    }
    public String getTelefon() {
        return this.telefon;
    }
    
    public void setTelefon(String telefon) {
        this.telefon = telefon;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set<Rasadnik> getRasadniks() {
        return this.rasadniks;
    }
    
    public void setRasadniks(Set<Rasadnik> rasadniks) {
        this.rasadniks = rasadniks;
    }
    public Set<Ocene> getOcenes() {
        return this.ocenes;
    }
    
    public void setOcenes(Set<Ocene> ocenes) {
        this.ocenes = ocenes;
    }


    public static void sacuvajPoljoprivrednika(Poljoprivrednik p){
         SessionFactory sf=HibernateUtil.getSessionFactory();
         Session session = sf.openSession();
         session.beginTransaction();
        
          session.save(p);
          session.getTransaction().commit();
          session.close();
    }
     public static List<Poljoprivrednik> dohvatiPoljoprivrednike(){
         List<Poljoprivrednik> poljoprivrednici=new ArrayList<Poljoprivrednik>();
          SessionFactory sf=HibernateUtil.getSessionFactory();
          Session session = sf.openSession();
          session.beginTransaction();
         
          String upit="from Poljoprivrednik p where p.korisnik.status=1";
          Query query = session.createQuery(upit);
          poljoprivrednici=query.list();
          
          session.getTransaction().commit();
          session.close();
          
          return poljoprivrednici;
         
 }
     public static void azuriraj(Poljoprivrednik  p){
         
          SessionFactory sf=HibernateUtil.getSessionFactory();
          Session session = sf.openSession();
          session.beginTransaction();
         
          session.update(p);
          
          session.getTransaction().commit();
          session.close();
            
     }
 


}


