package beans;
// Generated 17.05.2020. 19.35.51 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Set;
import javax.faces.model.SelectItem;
import org.hibernate.Criteria;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.criterion.Restrictions;
import util.HibernateUtil;

/**
 * Rasadnik generated by hbm2java
 */
public class Rasadnik  implements java.io.Serializable {


     private Integer idRas;
     private Poljoprivrednik poljoprivrednik;
     private String naziv;
     private String mesto;
     private int brZasadjenih;
     private int brSlobodnih;
     private int voda;
     private BigDecimal temperatura;
     private int duzina;
     private int sirina;
     private Set<Magacin> magacins = new HashSet<Magacin>(0);
     private Set<Narudzbina> narudzbinas = new HashSet<Narudzbina>(0);

    public Rasadnik() {
    }

	
    public Rasadnik(Poljoprivrednik poljoprivrednik, String naziv, String mesto, int brZasadjenih, int brSlobodnih, int voda, BigDecimal temperatura) {
        this.poljoprivrednik = poljoprivrednik;
        this.naziv = naziv;
        this.mesto = mesto;
        this.brZasadjenih = brZasadjenih;
        this.brSlobodnih = brSlobodnih;
        this.voda = voda;
        this.temperatura = temperatura;
    }
     public Rasadnik(Poljoprivrednik poljoprivrednik, String naziv, String mesto, int brZasadjenih, int brSlobodnih) {
        this.poljoprivrednik = poljoprivrednik;
        this.naziv = naziv;
        this.mesto = mesto;
        this.brZasadjenih = brZasadjenih;
        this.brSlobodnih = brSlobodnih;
        
    }
    public Rasadnik(Poljoprivrednik poljoprivrednik, String naziv, String mesto, int brZasadjenih, int brSlobodnih, int voda, BigDecimal temperatura, Set<Magacin> magacins, Set<Narudzbina> narudzbinas) {
       this.poljoprivrednik = poljoprivrednik;
       this.naziv = naziv;
       this.mesto = mesto;
       this.brZasadjenih = brZasadjenih;
       this.brSlobodnih = brSlobodnih;
       this.voda = voda;
       this.temperatura = temperatura;
       this.magacins = magacins;
       this.narudzbinas = narudzbinas;
    }

    public Rasadnik(Integer idRas, Poljoprivrednik poljoprivrednik, String naziv, String mesto, int brZasadjenih, int brSlobodnih, int voda, BigDecimal temperatura, int duzina, int sirina) {
        this.idRas = idRas;
        this.poljoprivrednik = poljoprivrednik;
        this.naziv = naziv;
        this.mesto = mesto;
        this.brZasadjenih = brZasadjenih;
        this.brSlobodnih = brSlobodnih;
        this.voda = voda;
        this.temperatura = temperatura;
        this.duzina = duzina;
        this.sirina = sirina;
    }
    
     public Rasadnik(Poljoprivrednik poljoprivrednik, String naziv, String mesto, int brZasadjenih, int brSlobodnih, int sirina, int duzina) {
        this.poljoprivrednik = poljoprivrednik;
        this.naziv = naziv;
        this.mesto = mesto;
        this.brZasadjenih = brZasadjenih;
        this.brSlobodnih = brSlobodnih;
        this.sirina = sirina;
        this.duzina = duzina;
        
    }
       public Rasadnik(Poljoprivrednik poljoprivrednik, String naziv, String mesto, int brZasadjenih, int brSlobodnih, int voda, BigDecimal temperatura, int duzina, int sirina) {
       
        this.poljoprivrednik = poljoprivrednik;
        this.naziv = naziv;
        this.mesto = mesto;
        this.brZasadjenih = brZasadjenih;
        this.brSlobodnih = brSlobodnih;
        this.voda = voda;
        this.temperatura = temperatura;
        this.duzina = duzina;
        this.sirina = sirina;
    }

    public int getDuzina() {
        return duzina;
    }

    public void setDuzina(int duzina) {
        this.duzina = duzina;
    }

    public int getSirina() {
        return sirina;
    }

    public void setSirina(int sirina) {
        this.sirina = sirina;
    }
    
    
   
    public Integer getIdRas() {
        return this.idRas;
    }
    
    public void setIdRas(Integer idRas) {
        this.idRas = idRas;
    }
    public Poljoprivrednik getPoljoprivrednik() {
        return this.poljoprivrednik;
    }
    
    public void setPoljoprivrednik(Poljoprivrednik poljoprivrednik) {
        this.poljoprivrednik = poljoprivrednik;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public String getMesto() {
        return this.mesto;
    }
    
    public void setMesto(String mesto) {
        this.mesto = mesto;
    }
    public int getBrZasadjenih() {
        return this.brZasadjenih;
    }
    
    public void setBrZasadjenih(int brZasadjenih) {
        this.brZasadjenih = brZasadjenih;
    }
    public int getBrSlobodnih() {
        return this.brSlobodnih;
    }
    
    public void setBrSlobodnih(int brSlobodnih) {
        this.brSlobodnih = brSlobodnih;
    }
    public int getVoda() {
        return this.voda;
    }
    
    public void setVoda(int voda) {
        this.voda = voda;
    }
    public BigDecimal getTemperatura() {
        return this.temperatura;
    }
    
    public void setTemperatura(BigDecimal temperatura) {
        this.temperatura = temperatura;
    }
    public Set<Magacin> getMagacins() {
        return this.magacins;
    }
    
    public void setMagacins(Set<Magacin> magacins) {
        this.magacins = magacins;
    }
    public Set<Narudzbina> getNarudzbinas() {
        return this.narudzbinas;
    }
    
    public void setNarudzbinas(Set<Narudzbina> narudzbinas) {
        this.narudzbinas = narudzbinas;
    }

    public static List<Rasadnik> dohvatiSveRasadnike(String username){
        List<Rasadnik> rasadnici=new ArrayList<Rasadnik>();
         SessionFactory sf = HibernateUtil.getSessionFactory();
         Session session = sf.openSession();
         session.beginTransaction();
         String upit="from Rasadnik r where r.poljoprivrednik.usernamePoljo=:username";
         Query query = session.createQuery(upit);
         query.setParameter("username", username);
         
         rasadnici=query.list();
         session.getTransaction().commit();
         session.close();
         return rasadnici;
    }
    
    public static void povecajTemp(Rasadnik rasadnik){
       rasadnik.setTemperatura(rasadnik.getTemperatura().add(BigDecimal.ONE));
       SessionFactory sf=HibernateUtil.getSessionFactory();
       Session session = sf.openSession();
       session.beginTransaction();
        
       session.update(rasadnik);
       session.getTransaction().commit();
       session.close();
        
    }
    
    public static void smanjiTemp(Rasadnik rasadnik){
        rasadnik.setTemperatura(rasadnik.getTemperatura().subtract(BigDecimal.ONE));
        SessionFactory sf=HibernateUtil.getSessionFactory();
        Session session = sf.openSession();
        session.beginTransaction();
        
        session.update(rasadnik);
        session.getTransaction().commit();
        session.close();
    }
    
    public static void dodajVodu(Rasadnik rasadnik){
        rasadnik.setVoda(rasadnik.getVoda()+1);
        SessionFactory sf=HibernateUtil.getSessionFactory();
        Session session = sf.openSession();
        session.beginTransaction();
        
        session.update(rasadnik);
        session.getTransaction().commit();
        session.close();
    }
    
    public static void smanjiVodu(Rasadnik rasadnik){
        rasadnik.setVoda(rasadnik.getVoda()-1);
        SessionFactory sf=HibernateUtil.getSessionFactory();
        Session session = sf.openSession();
        session.beginTransaction();
        
        session.update(rasadnik);
        session.getTransaction().commit();
        session.close();
    }
    
    public static Rasadnik dohvatiRasadnik(int idRasadnik){
         Rasadnik rasadnik;
         SessionFactory sf = HibernateUtil.getSessionFactory();
         Session session = sf.openSession();
         session.beginTransaction();
         String upit="from Rasadnik r where r.idRas=:idRasadnik";
         Query query = session.createQuery(upit);
         query.setParameter("idRasadnik", idRasadnik);
         
         rasadnik=(Rasadnik) query.uniqueResult();
         session.getTransaction().commit();
         session.close();
         
         return rasadnik;
    }
    
    
    public static LinkedList<SelectItem> rasadniciItems(String username){
        LinkedList<SelectItem> rasadniciIt=new LinkedList<SelectItem>();
        List<Rasadnik> rasadniciObj =Rasadnik.dohvatiSveRasadnike(username);
        for(int i=0; i<rasadniciObj.size(); i++){
            rasadniciIt.add(new SelectItem(rasadniciObj.get(i).idRas, rasadniciObj.get(i).naziv));
           
        }
        return rasadniciIt;
    }
    
    public static void dodajRasadnik(Rasadnik rasadnik){
        
        SessionFactory sf=HibernateUtil.getSessionFactory();
        Session session = sf.openSession();
        session.beginTransaction();
        
        session.save(rasadnik);
        session.getTransaction().commit();
        session.close();
        
    }
    
    
    public static void azurirajRasadnik(Rasadnik rasadnik){
        
        SessionFactory sf=HibernateUtil.getSessionFactory();
        Session session = sf.openSession();
        session.beginTransaction();
        
        session.update(rasadnik);
        session.getTransaction().commit();
        session.close();
        
    }
    
    public static List<Rasadnik> dohvatiRasadnikeSistema(){
        List<Rasadnik> rasadnici = new ArrayList<Rasadnik>();
        SessionFactory sf=HibernateUtil.getSessionFactory();
        Session session = sf.openSession();
        session.beginTransaction();
        
        rasadnici = session.createCriteria(Rasadnik.class).list();
        
        session.getTransaction().commit();
        session.close();
        return rasadnici;
        
    }
    
    public static List<String> dohvatiKriticneRasadnike(String username){
        List<String> kriticni=new ArrayList<String>();
        SessionFactory sf=HibernateUtil.getSessionFactory();
        Session session = sf.openSession();
        session.beginTransaction();
        
        String upit = "select r.naziv from Rasadnik r where r.poljoprivrednik.usernamePoljo = :username and (r.voda < 75 or r.temperatura < 12)";
        Query query = session.createQuery(upit);
        query.setParameter("username", username);
        kriticni = query.list();
        
        session.getTransaction().commit();
        session.close();
        return kriticni;
    }


}


