package beans;
// Generated 17.05.2020. 19.35.51 by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.List;
import org.hibernate.Criteria;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.criterion.Restrictions;
import util.HibernateUtil;




/**
 * Sadnica generated by hbm2java
 */
public class Sadnica  implements java.io.Serializable {


     private Integer idSad;
     private Magacin magacin;
     private Integer napredak;
     private int red;
     private int kolona;
     private int vremeDoVadjenja;
     

    public Sadnica() {
    }

	
    public Sadnica(Magacin magacin) {
        this.magacin = magacin;
    }
    public Sadnica(Magacin magacin, Integer napredak, int red, int kolona, int vremeDoVadjenja) {
       this.magacin = magacin;
       this.napredak = napredak;
       this.red=red;
       this.kolona=kolona;
       this.vremeDoVadjenja=vremeDoVadjenja;
    }

    public Sadnica(Integer idSad, Magacin magacin, Integer napredak, int red, int kolona, int vremeDoVadjenja) {
        this.idSad = idSad;
        this.magacin = magacin;
        this.napredak = napredak;
        this.red = red;
        this.kolona = kolona;
        this.vremeDoVadjenja=vremeDoVadjenja;
    }

    public int getVremeDoVadjenja() {
        return vremeDoVadjenja;
    }

    public void setVremeDoVadjenja(int vremeDoVadjenja) {
        this.vremeDoVadjenja = vremeDoVadjenja;
    }
    
    
    
    

    public int getRed() {
        return red;
    }

    public void setRed(int red) {
        this.red = red;
    }

    public int getKolona() {
        return kolona;
    }

    public void setKolona(int kolona) {
        this.kolona = kolona;
    }
    
    
   
    public Integer getIdSad() {
        return this.idSad;
    }
    
    public void setIdSad(Integer idSad) {
        this.idSad = idSad;
    }
    public Magacin getMagacin() {
        return this.magacin;
    }
    
    public void setMagacin(Magacin magacin) {
        this.magacin = magacin;
    }
    public Integer getNapredak() {
        return this.napredak;
    }
    
    public void setNapredak(Integer napredak) {
        this.napredak = napredak;
    }

   public static List<Sadnica> dohvatiSveSadnice(int idRasadnik){
       List<Sadnica> sadnice = new ArrayList<Sadnica>();
        SessionFactory sf = HibernateUtil.getSessionFactory();
         Session session = sf.openSession();
         session.beginTransaction();
         String upit="from Sadnica s where s.magacin.rasadnik.idRas = :idRasadnik";
         Query query = session.createQuery(upit);
         query.setParameter("idRasadnik", idRasadnik);
         
         sadnice=query.list();
         session.getTransaction().commit();
         session.close();
         return sadnice;
   }
   
   public static Sadnica dohvatiSadnicu(int red, int kolona,int idRasadnik){
         Sadnica sadnica=new Sadnica();
         SessionFactory sf = HibernateUtil.getSessionFactory();
         Session session = sf.openSession();
         session.beginTransaction();
         String upit="from Sadnica s where s.magacin.rasadnik.idRas = :idRasadnik and s.red = :red and s.kolona = :kolona";
         Query query = session.createQuery(upit);
         query.setParameter("idRasadnik", idRasadnik);
         query.setParameter("red", red);
         query.setParameter("kolona", kolona);
         
         sadnica=(Sadnica) query.uniqueResult();
        
         session.getTransaction().commit();
         session.close();
         return sadnica;
   }
   
   
   public static String dohvatiNazivSadnice(int idSadnica){
         String ret="SLOBODNO";
         SessionFactory sf = HibernateUtil.getSessionFactory();
         Session session = sf.openSession();
         session.beginTransaction();
         Criteria c = session.createCriteria(Sadnica.class);
         Sadnica sadnica = (Sadnica) c.add(Restrictions.eq("idSad", idSadnica)).uniqueResult();
         session.getTransaction().commit();
         session.close();
         if(sadnica!=null){
             ret=sadnica.getMagacin().getOnlineprodavnica().getNaziv();
         }
       return ret;
   }
   
   public static void dodajSadnicu(Magacin magacin, int red, int kolona){
        Sadnica sadnica=new Sadnica(magacin,0,red,kolona,0);
       
        SessionFactory sf=HibernateUtil.getSessionFactory();
        Session session = sf.openSession();
        session.beginTransaction();
        
        session.save(sadnica);
        
        session.getTransaction().commit();
        session.close();
   }
   
   public static void ubrzajNapredak(Magacin preparat, Sadnica sadnica){
       sadnica.setNapredak(sadnica.getNapredak()+preparat.getOnlineprodavnica().getUputstvo());
       SessionFactory sf=HibernateUtil.getSessionFactory();
       Session session = sf.openSession();
       session.beginTransaction();
        
       session.update(sadnica);
       
       session.getTransaction().commit();
       session.close();
   }
   
   public static void izvadiSadnicu(Sadnica sadnica){
       SessionFactory sf=HibernateUtil.getSessionFactory();
       Session session = sf.openSession();
       session.beginTransaction();
        
       session.delete(sadnica);
       session.getTransaction().commit();
       session.close();
   }
   
   public static void azurirajSadnicu(Sadnica s){
       SessionFactory sf=HibernateUtil.getSessionFactory();
       Session session = sf.openSession();
       session.beginTransaction();
        
       session.update(s);
       session.getTransaction().commit();
       session.close();
   }
   
   public static List<Sadnica> dohvatiIzvadjeneSadnice(){
       List<Sadnica> sadnice=new ArrayList<Sadnica>();;
       SessionFactory sf=HibernateUtil.getSessionFactory();
       Session session = sf.openSession();
       session.beginTransaction();
        
       String upit="from Sadnica s where s.vremeDoVadjenja>0";
       Query query = session.createQuery(upit);
       sadnice=query.list();
      
       session.getTransaction().commit();
       session.close();
       
       return sadnice;
   }


}


